---
dist: trusty
sudo: false

language: python
python: 3.6

script:
  - make test

deploy:
  provider: script
  script: |-
    curl -H "Content-Type: application/json" --data '{"build": true}' -X POST \
        https://registry.hub.docker.com/u/naftulikay/trusty-vm/trigger/${DOCKERHUB_TOKEN}/

notifications:
  email:
    on_success: never
    on_failure: never
