---
dist: trusty
sudo: false

matrix:
  fast_finish: true

services:
  - docker

install: true

script:
  - make test-clean

notifications:
  email:
    on_success: never
    on_failure: never
  webhooks: https://registry.hub.docker.com/u/naftulikay/trusty-vm/trigger/${DOCKERHUB_TOKEN}/
